# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCMzbTUHUz2qecM9OyZkg-P68QXZqvbq
"""

from flask import Flask, request, render_template
from tensorflow.keras.models import load_model
import os

!rm -rf veinsecure-palm-vein-authentication
!git clone https://github.com/anjorisarabhai/veinsecure-palm-vein-authentication.git

import sys
sys.path.append('/content/veinsecure-palm-vein-authentication')

!touch /content/veinsecure-palm-vein-authentication/utils/__init__.py

!wget -O /content/veinsecure-palm-vein-authentication/utils/helpers.py https://raw.githubusercontent.com/anjorisarabhai/veinsecure-palm-vein-authentication/main/utils/helpers.py

!ls -R /content/veinsecure-palm-vein-authentication

import os
print(os.listdir('/content/veinsecure-palm-vein-authentication/utils'))

!ls /content/veinsecure-palm-vein-authentication/utils
!sed -n '1,20p' /content/veinsecure-palm-vein-authentication/utils/helpers.py

!head -n 165 /content/veinsecure-palm-vein-authentication/utils/helpers.py

import importlib
import utils.helpers
importlib.reload(utils.helpers)

from utils.helpers import predict_image

app = Flask(__name__)

!git lfs install

model = load_model("veinsecure-palm-vein-authentication/results/models/final_model.h5")

# Ensure uploads directory exists
UPLOAD_FOLDER = "static/uploads/"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route('/')
def home():
    return "✅ Flask App Running! (UI coming soon)"

if __name__ == '__main__':
    app.run(debug=True)

